### ISSUE TITLE
Add necessary packages to requirements.txt 

### ISSUE THREAD

**Issue by PannagaRao** [karthikmp5/C.E.L.T_pro#13]
Add the required packages to requirements.txt.

**Comment by Harshitha199819** [comment]
Fixed-79cac68f045b91c115d602fd620385ba0a5e6e3b

**Comment by Harshitha199819** [comment]
Fixed-79cac68f045b91c115d602fd620385ba0a5e6e3b

**Comment by PannagaRao** [comment]
Maintain the consistency between ~= and >= in the requirements.txt file

**Comment by Harshitha199819** [comment]
This is resolved
